services:
  postgresql:
    image: postgres:18
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hyuk
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: delivery_eum
    volumes:
      - ./data/pgdata:/var/lib/postgresql
      - ./data/postgres:/docker-entrypoint-initdb.d
    networks:
      delivery-network:
  redis:
    image: redis:7.4-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./data/redis:/data
    networks:
      delivery-network:

networks:
  delivery-network:
    driver: bridge