services:
  postgresql:
    image: postgis/postgis:17-3.5
    command: ["postgres", "-c", "wal_level=logical", "-c", "work_mem=128MB", "-c", "shared_buffers=256MB", "-c", "max_connections=300"]
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hyuk
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: delivery_eum
    volumes:
      - ./data/pgdata:/var/lib/postgresql
      - ./data/postgres:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      delivery-network:

  redis:
    image: redis:7.4-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass ${POSTGRES_PASSWORD}
    volumes:
      - ./data/redis:/data
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      delivery-network:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.8.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      delivery-network:

  kafka:
    image: confluentinc/cp-kafka:7.8.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    deploy:
      resources:
        limits:
          memory: 2G
    networks:
      delivery-network:
  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.8.0
    container_name: kafka-connect
    depends_on:
      - kafka
      - postgresql
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:29092
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_GROUP_ID: "connect-cluster"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
    command:
      - bash
      - -c
      - |
        echo "Installing Debezium Connector..."
        confluent-hub install --no-prompt debezium/debezium-connector-postgresql:2.5.4
        echo "Installation completed. Starting Kafka Connect..."
        /etc/confluent/docker/run
    deploy:
      resources:
        limits:
          memory: 2G
    networks:
      delivery-network:

  connector-setup:
    image: alpine:latest
    container_name: connector-setup
    depends_on:
      - kafka-connect
    volumes:
      - ./connect:/config
    entrypoint:
      - /bin/sh
      - -c
      - |
        apk add --no-cache curl bash dos2unix
        dos2unix /config/setup-connector.sh
        bash /config/setup-connector.sh
    networks:
      delivery-network:

  nominatim:
    image: mediagis/nominatim:4.5
    container_name: nominatim
    ports:
      - "8088:8080"
    environment:
      PBF_URL: ${NOMINATIM_PBF_URL:-https://download.geofabrik.de/asia/south-korea-latest.osm.pbf}
      REPLICATION_URL: https://download.geofabrik.de/asia-updates/
      NOMINATIM_PASSWORD: ${NOMINATIM_PASSWORD}
    shm_size: "2gb"
    volumes:
      - ./data/nominatim:/var/lib/postgresql/14/main
    deploy:
      resources:
        limits:
          memory: 8G
    networks:
      delivery-network:

  mockserver:
    image: mockserver/mockserver:5.15.0
    container_name: mockserver
    ports:
      - "9999:1080"
    volumes:
      - ./mockserver/config:/config
    environment:
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/expectations.json
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      delivery-network:

  ngrinder-controller:
    image: ngrinder/controller:3.5.9
    container_name: ngrinder-controller
    ports:
      - "8888:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    volumes:
      - ./data/ngrinder-controller:/opt/ngrinder-controller
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      delivery-network:

  ngrinder-agent:
    image: ngrinder/agent:3.5.9
    container_name: ngrinder-agent
    depends_on:
      - ngrinder-controller
    links:
      - ngrinder-controller:controller
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      delivery-network:

  jaeger:
    image: jaegertracing/all-in-one:1.55
    container_name: jaeger
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "6831:6831/udp"
      - "4317:4317"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      delivery-network:

networks:
  delivery-network:
    driver: bridge