server:
  tomcat:
    threads:
      max: 250
      min-spare: 50
  port: 9101

spring:
  profiles:
    active: dev
  application:
    name: restaurant-service
  threads:
    virtual:
      enabled: true
  datasource:
    hikari:
      maximum-pool-size: 40
      minimum-idle: 20
      connection-timeout: 10000
#    url: jdbc:postgresql://localhost:5432/delivery_eum
    url: jdbc:postgresql://localhost:5432/delivery_eum?reWriteBatchedInserts=true
    username: hyuk
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
  data:
    redis:
      host: localhost
      port: 6379

#logging:
#  level:
#    com.hyuk.restaurant.service: DEBUG

#management:
#  tracing:
#    sampling:
#      probability: 1.0
#  otlp:
#    tracing:
#      endpoint: http://localhost:4318/v1/traces
#
#feign:
#  observation:
#    enabled: true
#  httpclient:
#    enabled: false
#  hc5:
#    enabled: true