server:
  port: 9092

spring:
  profiles:
    active: dev
  application:
    name: restaurant-service
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_eum
    username: hyuk
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect